#dir and path 
baseurl: /mylog
exclude: ['README.md']
permalink: /:path

#syntax
markdown: kramdown
highlighter: rouge




#collections here

collections:

    codeCollection:
          output: true
          permalink: /codes/:path

    softwareCollection:
          output: true
          permalink: /softwares/:path

    techCollection:
        output: true
        permalink: /technology/:path

    fitnessCollection:
        output: true
        permalink: /fitness/:path

#plugins

gems: [jekyll-timeago]
