#syntax
markdown: kramdown
highlighter: rouge
#dir and path 
#baseurl: /mylog
permalink: /:path
env : 'production'
# env : 'development'


exclude:
  - "bower_components"
  - "node_modules"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"
  - "Gruntfile.coffee"
  - "package.json"
  - "Rakefile"
  - "README.md"


#collections here

collections:

    postCollection: 
          output: true
          permalink: /posts/:path
    authors:
        output: true
        permalink: /about/:path

#plugins

plugins:
  - jekyll-seo-tag





#social and seo
name: '{init}|grep'
title: www.initgrep.com
description: Blog about Software development, languages and other tech stuff
logo: logo.jpg
image: logo.jpg 

twitter:
  username: initgrep

facebook:
  username: initgrep






