#syntax
markdown: kramdown
highlighter: rouge
#dir and path 
#baseurl: /mylog
permalink: /:path


exclude:
  - "bower_components"
  - "node_modules"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"
  - "Gruntfile.coffee"
  - "package.json"
  - "Rakefile"
  - "README.md"


#collections here

collections:

    postCollection: 
          output: true
          permalink: /posts/:path
    authors:
        output: true
        permalink: /about/:path

#plugins

gems:
  - jekyll-seo-tag





#social and seo

title: shaykhslog.com
description: Blog about techonology, code, Health and fitness
logo: logo.jpg
image: logo.jpg 

twitter:
  username: shaykhslog

facebook:
  username: shaykhslog






