#syntax
markdown: kramdown
highlighter: rouge
#dir and path 
baseurl: /mylog
permalink: /:path


exclude:
  - "bower_components"
  - "node_modules"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"
  - "Gruntfile.coffee"
  - "package.json"
  - "Rakefile"
  - "README.md"


#collections here

collections:

    codeCollection:
          output: true
          permalink: /codes/:path

    lifeCollection:
          output: true
          permalink: /life/:path

    techCollection:
        output: true
        permalink: /technology/:path

    fitnessCollection:
        output: true
        permalink: /fitness/:path

#plugins

gems:
  - jekyll-seo-tag
  - octopress-paginate





#social and seo

title: shaykh'slog- Blog about technology and life
#email
description: Blog about technology, coding , fitness and coding
url : gagrock.github.io
logo: /assets/images/logo.jpg
author:
  twitter: shk_irshad

#social profile
social:
  name: irshad sheikh
  links:
    - https://twitter.com/shk_irshad
    - https://www.facebook.com/irshsheikh
   # - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+irshad.mike
    - https://github.com/gagrock
   # - https://keybase.io/benbalter

twitter:
  username: irshsheikh

facebook:
  app_id: 1234
  publisher: pub_123
  admins: scrollasd




